### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by zzlzzg** [smuyyh/BankCardFormat#3]
/**
     * 校验银行卡卡号
     */
    public boolean checkBankCard(String cardId) {

        if (TextUtils.isEmpty(cardId)) {
            return false;
        }

        char bit = getBankCardCheckCode(cardId.substring(0, cardId.length() - 1));
        if (bit == 'N') {
            return false;
        }
        return cardId.charAt(cardId.length() - 1) == bit;
    }

用博主的项目,谢谢

**Comment by smuyyh** [comment]
好的 谢谢。后面改一下~
