### ISSUE TITLE
del按键 后 页面闪退

### ISSUE THREAD

**Issue by zwjhit** [smuyyh/BankCardFormat#7]

**Comment by zwjhit** [comment]
清空所有数据 就闪退

**Comment by agirllmy** [comment]
01-23 15:26:13.106 14534 14534 E AndroidRuntime: FATAL EXCEPTION: main
01-23 15:26:13.106 14534 14534 E AndroidRuntime: Process: com.yuyh.bankcardformat, PID: 14534
01-23 15:26:13.106 14534 14534 E AndroidRuntime: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=-1
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at java.lang.String.startEndAndLength(String.java:298)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at java.lang.String.substring(String.java:1087)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at com.example.library.BandCardEditText.checkBankCard(BandCardEditText.java:102)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at com.example.library.BandCardEditText.isBankCard(BandCardEditText.java:95)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at com.example.library.BandCardEditText.format(BandCardEditText.java:81)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at com.example.library.BandCardEditText.access$000(BandCardEditText.java:10)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at com.example.library.BandCardEditText$CardTextWatcher.afterTextChanged(BandCardEditText.java:53)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at android.widget.TextView.sendAfterTextChanged(TextView.java:8007)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10168)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1043)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:560)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:225)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:224)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at android.view.inputmethod.BaseInputConnection.deleteSurroundingText(BaseInputConnection.java:244)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:389)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-23 15:26:13.106 14534 14534 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by smuyyh** [comment]
解决了。不过数据比较老了，目前有些银行检测不出来，所以没怎么维护了。
